---
#buid project
#- name: build app
#shell: ng build --configuration=production
 
# tasks file for buildDocker
##### provision brand new ubuntu 18.04 server

# ...

##### setup group and user

- name: create docker group
  become: true
  group:
    name: docker
    state: present

- name: add user to group 
  become: true
  user:
    name: "{{ansible_user}}"
    groups: docker
    append: true

- meta: reset_connection                # <--- must do this if using pipelining

##### setup docker
- name: create image docker
  docker_image:
    name: pfe2020
    build:
     path: /var/lib/jenkins/workspace/pfe2020
     pull: no
    source: build
    state: present
    force_source: true
- name: run container docker
  docker_container:
    name: myapp_container
    image: pfe2020:latest
    state: started
    recreate: true
    ports:
     - "4200:80"
